sudo: required
services:
  - docker

before_install:
  - openssl -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;                         # Download Google Cloud SDK
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl                                              # Install and update Kubectl on Travis
  - gcloud auth activate-service-account --key-file service-account.json
  - docker build -t idhruven/react-test -f ./client/Dockerfile.dev ./client