apiVersion: apps/v1                         #Set of Object Types
kind: Deployment                            #Kind (Type) of Object
metadata:
  name: client-deployment                   #Name of the Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000